### ISSUE TITLE
Issue when start server.

### ISSUE THREAD

**Issue by FaanMaario** [minecraftgenius76/Spleef#1]
Hi.
I've installed this plugin on my server, but when I launch it, my server crash instantly.

Here, the crashdump document: https://docs.google.com/file/d/0B1zyNGYeW8RRYk1idnNZNzRjaVU/edit?usp=docslist_api

Thanks.

**Comment by minecraftgenius76** [comment]
Hi, the reason for the crash was missing messages_EN.yml file under this
plugin configuration folder [mcg76_spleef], I should install automatically
unless you have older version of spleef running. Please temporary rename
previous version configuration folder then try restart your server again.
Let me know if this works?

**Comment by minecraftgenius76** [comment]
sorry - actually for some reason the root cause of the problem was
config.xml file is empty.  trying to fix this.

**Comment by minecraftgenius76** [comment]
Hi, try this new version Spleef version 1.5.1 -  fixed first time installation error with empty configuration file http://www.mediafire.com/download/vc98226u6yvye31/mcg76_Spleef_v1.5.1.phar
