### ISSUE TITLE
Correct Install?

### ISSUE THREAD

**Issue by Awzaw** [minecraftgenius76/Spleef#13]
Hi, I had a lot of trouble installing this... but seemed to have succeeded thanks mostly to trial and error as I found the docs impossible to follow, and I'm a programmer :-/

So it's working, but I get loads of errors, possibly because I may not have installed correctly. In particular I spend a long time trying to find the map ZIP... and when I did find it (not on github or the youtube video, but on some Japanese website) I didn't know where to put it - in the PM worlds folder or the plugin folder?

09.03 07:11:58 [Server] NOTICE InvalidArgumentException: "Argument 1 passed to mcg76\game\spleef\SpleefArenaBuilder::buildFloor() must be an instance of pocketmine\level\Level, null given, called in phar:///plugins/mcg76_Spleef_v1.5.5.phar/src/mcg76/game/spleef/SpleefArenaBuilder.php on line 81 and defined" (E_RECOVERABLE_ERROR) in "/mcg76_Spleef_v1.5.5.phar/src/mcg76/game/spleef/SpleefArenaBuilder" at line 157
09.03 07:11:58 [Server] CRITICAL Could not execute task mcg76\game\spleef\tasks\PlayResetTimeout: Argument 1 passed to mcg76\game\spleef\SpleefArenaBuilder::buildFloor() must be an instance of pocketmine\level\Level, null given, called in phar:///plugins/mcg76_Spleef_v1.5.5.phar/src/mcg76/game/spleef/SpleefArenaBuilder.php on line 81 and defined
09.03 07:11:58 [Server] INFO Error :world has NOT generated yet!
09.03 07:11:58 [Server] Startup Done (1.126s)! For help, type "help" or "?"

**Comment by minecraftgenius76** [comment]
welcome to pocketmine programming. You know when I start working on pocketmine progrramming is all about doing myself trial and errors,

For deployment of this game, is very straight forward. unzip the map to pocketmine server / worlds folder and put the plugin in server plugin folder. then restart the server should work.

based on the error you pasted, the cause of the error was due to missing configuration on the world name, the best way to help you is tell me what is been deployed in your server worlds directory and your plugin configurations settings. I can help you.

**Comment by Awzaw** [comment]
Thanks for getting back to me - I think that has helped me fixed the error :-)

**Comment by MrKayaba** [comment]
I am having the same issue, but also for tnt run

**Comment by MrKayaba** [comment]
My issue with both is

[20:08:06] [Server thread/INFO]: [mcg76_Spleef] Error :world has NOT generated yet!
[20:08:06] [Server thread/INFO]: [mcg76_Spleef] Argument 1 passed to mcg76\game\spleef\SpleefArenaBuilder::buildFloor() must be an instance of pocketmine\level\Level, null given, called in phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/plugins/mcg76_Spleef_v1.6.0.phar/src/mcg76/game/spleef/SpleefArenaBuilder.php on line 62 and defined|167|#0 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/plugins/mcg76_Spleef_v1.6.0.phar/src/mcg76/game/spleef/SpleefArenaBuilder.php(167): ExceptionHandler::handler(4096, 'Argument 1 pass...', 'phar://C:/Users...', 167, Array)
#1 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/plugins/mcg76_Spleef_v1.6.0.phar/src/mcg76/game/spleef/SpleefArenaBuilder.php(62): mcg76\game\spleef\SpleefArenaBuilder->buildFloor(NULL, '535', 20, '409', 26, 49, 'inside')
#2 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/plugins/mcg76_Spleef_v1.6.0.phar/src/mcg76/game/spleef/tasks/PlayResetTimeout.php(46): mcg76\game\spleef\SpleefArenaBuilder->buildStadiumFloorOnly('world', Object(pocketmine\level\Position), '16')
#3 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/TaskHandler.php(150): mcg76\game\spleef\tasks\PlayResetTimeout->onRun(1)
#4 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/ServerScheduler.php(247): pocketmine\scheduler\TaskHandler->run(1)
#5 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php(2479): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(1)
#6 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php(2222): pocketmine\Server->tick()
#7 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php(2100): pocketmine\Server->tickProcessor()
#8 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php(1701): pocketmine\Server->start()
#9 phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php(464): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), 'phar://C:/Users...', 'C:\Users\Jose\D...', 'C:\Users\Jose\D...')
#10 C:\Users\Jose\Desktop\Pocketmine-Hyraid\PocketMine-MP\PocketMine-MP.phar(1): require('phar://C:/Users...')
#11 {main}

Fatal error: Call to a member function getTile() on null in phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/plugins/mcg76_TNTRun_v1.6.0.phar/src/mcg76/game/tntrun/PlayResetTimeout.php on line 126

Call Stack:
    0.0656     444920   1. {main}() C:\Users\Jose\Desktop\Pocketmine-Hyraid\PocketMine-MP\PocketMine-MP.phar:0
    0.0719     439952   2. require('phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Jose\Desktop\Pocketmine-Hyraid\PocketMine-MP\PocketMine-MP.phar:1
    0.5063     581232   3. pocketmine\Server->__construct() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
   11.3838   20606448   4. pocketmine\Server->start() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1701
   11.4036   20622304   5. pocketmine\Server->tickProcessor() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2100
   11.4036   20622776   6. pocketmine\Server->tick() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2222
   11.4055   20623840   7. pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2479
   11.4143   20624952   8. pocketmine\scheduler\TaskHandler->run() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/ServerScheduler.php:247
   11.4143   20625672   9. mcg76\game\tntrun\PlayResetTimeout->onRun() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/TaskHandler.php:150
   11.4143   20625984  10. mcg76\game\tntrun\PlayResetTimeout->updateSigns() phar://C:/Users/Jose/Desktop/Pocketmine-Hyraid/PocketMine-MP/plugins/mcg76_TNTRun_v1.6.0.phar/src/mcg76/game/tntrun/PlayResetTimeout.php:29

**Comment by AndreyNazarchuk** [comment]
It's broken, make your own

**Comment by MrKayaba** [comment]
is there a way to fix the broken parts of both tntrun and spleef plugins, if not, then how do I make mine or where could I find another one for both

**Comment by AndreyNazarchuk** [comment]
Google is your best friend

**Comment by ghost** [comment]
if you give me the phar i will upfate it for you
