### ISSUE TITLE
76 a problem about your plugin

### ISSUE THREAD

**Issue by alcmoe** [minecraftgenius76/Spleef#7]
Just now I find a chat group,they sale your CTF.
A CTF ,they sale 14$.....

Really damn guy.

**Comment by minecraftgenius76** [comment]
Wow, thanks for telling me. Do you know who?

**Comment by alcmoe** [comment]
![m](https://cloud.githubusercontent.com/assets/9844277/5932651/19425980-a6ed-11e4-9b60-2b8325d140c6.png)
means sale CTF,and CTF maps,and Usage
.really ashamed

**Comment by minecraftgenius76** [comment]
Thanks again Alcatraz for telling me. holy, that is illegal to steal someone work for own profit. I didn't license him for any commercial use, all mini-games I made are for personal use at this moment.  I appreciate if you can send me the link, I will send him a warning and let people know they should ask for a refund. 

on a second note, I am planning to create a separate web site for mini-games downloads/forum. I may ask your help later if you don't might.  Thanks in advance.

**Comment by Lunfeng** [comment]
I know this man.......
